name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set ref
        id: ref
        run: echo ::set-output name=ref::${GITHUB_REF#refs/*/}
      - 
        name: Set tag
        id: tag
        run: echo ::set-output name=$(echo ${{ steps.vars.outputs.ref }} | sed "s/[^[:alnum:]]/./g")
      - 
        name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo ref=${{ steps.vars.outputs.ref }}
          echo tag=${{ steps.vars.outputs.tag }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uapf-space-deploy-webhook:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
